version: '3.8'
services:
db:
image: postgres:15
restart: unless-stopped
environment:
POSTGRES_DB: istos_qms
POSTGRES_USER: istos
POSTGRES_PASSWORD: istospass
volumes:
- db_data:/var/lib/postgresql/data
ports:
- 5432:5432


app:
build: ./backend
depends_on:
- db
environment:
DB_NAME: istos_qms
DB_USER: istos
DB_PASS: istospass
DB_HOST: db
DB_PORT: 5432
JWT_SECRET: "wt4tphhhtxcyqpp"
volumes:
- ./backend:/usr/src/app
ports:
- 4000:4000


volumes:
db_data:

